config/routes.rb
Gesco::Application.routes.draw do 
  resources :rolagents

  resources :attendants

  resources :meetings

  resources :docs

  resources :commissions

  resources :units

  resources :agents

  resources :values
	

   root :to => "user_sessions#new"

  Gesco::Application.routes.draw do
    resources :agents, :user_sessions, :rolagents, :attendants, :commissions
    match 'login' => 'user_sessions#new', :as => :login
    match 'logout' => 'user_sessions#destroy', :as => :logout
    match 'rolagents/search/:id' => 'rolagents#search'
    match 'attendants/search/:id' => 'attendants#search'
    match 'commissions/pdf/:id/:a' => 'commissions#pdf'
    match 'commissions/searchbyunit/:id' => 'commissions#searchbyunit'
    match 'rolagents/searchbycomm/:id' => 'rolagents#searchbycomm'
    match 'rolagents/searchbycomm/:id/:u' => 'rolagents#searchbycomm'
    match 'meetings/searchbycomm/:id' => 'meetings#searchbycomm'
    match 'docs/searchbycomm/:id' => 'docs#searchbycomm'
    match 'docs/searchbymeet/:id' => 'docs#searchbymeet'
    match 'commissions/new/:id' => 'commissions#new'
    match 'meetings/new/:id' => 'meetings#new'
    match 'rolagents/new/:id/:u' => 'rolagents#new'
    match 'docs/new/:id' => 'docs#new'
    match 'docs/new/:id' => 'docs#new'
  end

end

app/models/rolagent.rb
# -*- encoding : utf-8 -*-
class Rolagent < ActiveRecord::Base
  belongs_to :rol, :class_name => "Value"
  belongs_to :agent
  belongs_to :unit
  belongs_to :commission
  belongs_to :estado, :class_name => "Value"
end

app/controllers/rolagents_controller.rb
# -*- encoding : utf-8 -*-
class RolagentsController < ApplicationController

  def search
    unless current_user.nil?
      if is_admin || is_admin_UO || (current_user.id.to_s == params[:id])
        @search = params[:id];
        @rolagents = Rolagent.find(:all, :conditions => {:agent_id => params[:id]})
        render :index
      else
        render_500
      end
    else
      redirect_to_login
    end
  end

  # GET /rolagents
  # GET /rolagents.xml
  def index
    if is_admin || is_admin_UO
      @rolagents = Rolagent.all
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @rolagents }
      end
    else
      @rolagents = Rolagent.find(:all, :conditions => {:agent_id => current_user.id})
    end
  end
  
  def searchbycomm
     unless current_user.nil?
        @searchbycomm = params[:id]
        @rolagents = Rolagent.find(:all, :conditions => {:commission_id => params[:id] })
        render :index
     else 
      redirect_to_login
     end
  end

  # GET /rolagents/1
  # GET /rolagents/1.xml
  def show
    @rolagent = Rolagent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rolagent }
    end
  end

  # GET /rolagents/new
  # GET /rolagents/new.xml
  def new
    unless current_user.nil?
      if is_admin || is_admin_UO || is_secre
        @rolagent = Rolagent.new
        respond_to do |format|
          format.html # new.html.erb
          format.xml  { render :xml => @rolagent }
        end
      else 
        render_500
      end
    else
      redirect_to_login
    end
  end

  # GET /rolagents/1/edit
  def edit
    unless current_user.nil?
      if is_admin || is_admin_UO || is_secre
        @rolagent = Rolagent.find(params[:id])
      else 
        render_500
      end
    else
      redirect_to_login
    end
  end

  # POST /rolagents
  # POST /rolagents.xml
  def create
    unless current_user.nil?
      if is_admin || is_admin_UO || is_secre
        @rolagent = Rolagent.new(params[:rolagent])
        respond_to do |format|
          if @rolagent.save
            format.html { redirect_to("/rolagents/searchbycomm/" + @rolagent.commission.id.to_s, :notice => 'Rol creado satisfactoriamente.') }
            format.xml  { render :xml => @rolagent, :status => :created, :location => @rolagent }
          else
            format.html { render :action => "new" }
            format.xml  { render :xml => @rolagent.errors, :status => :unprocessable_entity }
          end
        end
      else 
        render_500
      end
    else
      redirect_to_login
    end

  end

  # PUT /rolagents/1
  # PUT /rolagents/1.xml
  def update
    unless current_user.nil?
      if is_admin || is_admin_UO || is_secre
        @rolagent = Rolagent.find(params[:id])
        respond_to do |format|
          if @rolagent.update_attributes(params[:rolagent])
            format.html { redirect_to("/rolagents/searchbycomm/" + @rolagent.commission.id.to_s, :notice => 'Rol editado satisfactoriamente.') }
            format.xml  { head :ok }
          else
            format.html { render :action => "edit" }
            format.xml  { render :xml => @rolagent.errors, :status => :unprocessable_entity }
          end
        end
      else 
        render_500
      end
    else
      redirect_to_login
    end
  end

  # DELETE /rolagents/1
  # DELETE /rolagents/1.xml
  def destroy
    unless current_user.nil?
      if is_admin || is_admin_UO || is_secre
        @rolagent = Rolagent.find(params[:id])
        @rolagent.destroy
        respond_to do |format|
          format.html { redirect_to(:back) }
          format.xml  { head :ok }
        end
      else 
        render_500
      end
    else
      redirect_to_login
    end
  end
end

app/helpers/rolagents_helper.rb
# -*- encoding : utf-8 -*-
module RolagentsHelper
end

app/views/rolagents/_form.html.erb
<%= form_for(@rolagent, :html => { :class => "formulario"}) do |f| %>
  <% if @rolagent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rolagent.errors.count, "error") %> prohibited this rolagent from being saved:</h2>

      <ul>
      <% @rolagent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Rol" %><br />
    <% if is_admin %>
      <% if params[:op].nil? %>     
	     <% @roles = Value.find(:all, :conditions => 'codigo like "6.3" OR codigo like "6.4" OR codigo like "6.5" ').map { |t| [t.codigo + ', ' + t.description, t.id] } %>
      <% else %>
         <% @roles = Value.find(:all, :conditions => 'codigo like "6.1" OR codigo like "6.2" ').map { |t| [t.codigo + ', ' + t.description, t.id] } %>
      <%end%>
    <% else %>
      <% if is_admin_UO %>
         <% @roles = Value.find(:all, :conditions => 'codigo like "6.3"').map { |t| [t.codigo + ', ' + t.description, t.id] } %>
      <% else %>
         <% if is_secre %>
            <% @roles = Value.find(:all, :conditions => ['codigo like "6.4" OR codigo like "6.5"'] ).map { |t| [t.codigo + ', ' + t.description, t.id] } %>
         <% end %>
      <% end %>      
   <% end %>
    <%= f.select :rol_id, @roles, {:include_blank => true} %>

  </div>
  <div class="field">
    <%= f.label "Usuario" %><br />
	 <% unless params[:op].nil? %>
	 <% @a = Agent.find(:all, :conditions => {:id => params[:op]}).map{ |aa| [aa.id]} %>
	 <% @agents = Agent.find(:all).map { |t| [t.usuario, t.id] } %>
    <%= f.select :agent_id, @agents, :selected => @a %>
	 <% else %>
	 <% @agents = Agent.find(:all).map { |t| [t.usuario, t.id] } %>
    <%= f.select :agent_id, @agents, {:include_blank => true} %>
	 <% end %>
  </div>
  <div class="field">
    <%= f.label "Unidad Organizativa" %><br />
	 <% unless params[:id].nil? and params[:u].nil? %>
	 	<% @units = Unit.find(:all, :conditions => {:id => params[:u]}).map { |t| [t.nombre, t.id] } %>
    	<%= f.select :unit_id, @units %>
	 <% else %>
	 	<% @units = Unit.find(:all, :conditions => ['id != 0']).map { |t| [t.nombre, t.id] } %>
    	<%= f.select :unit_id, @units, {:include_blank => true} %>
	 <% end %>
  </div>
  <div class="field">
    <%= f.label :"Comisión" %><br />
	 <% unless params[:id].nil? and params[:u].nil? %>
		 <% @commissions = Commission.find(:all, :conditions => {:id => params[:id]}).map { |t| [t.nombre, t.id] } %>
    	 <%= f.select :commission_id, @commissions %>
	 <% else %>
		 <% @commissions = Commission.find(:all, :conditions => {:id => 0}).map { |t| [t.nombre, t.id] } %>
  	    <%= f.select :commission_id, @commissions %>
	 <% end %>
  </div>
  <div class="field">
    <%= f.label "Fecha de Alta" %><br />
    <%= f.datetime_select :fechaalta %>
  </div>
  <div class="field">
    <%= f.label "Fecha de Baja" %><br />
    <%= f.datetime_select :fechabaja, {:include_blank => true} %>
  </div>
  <div class="field">
    <%= f.label "Motivo de la Baja" %><br />
    <%= f.text_area :motivobaja %>
  </div>
  <div class="field">
    <%= f.label "Estado" %><br />
	 <% @estados = Value.find(:all, :conditions => 'codigo like "1._"').map { |t| [t.codigo + ', ' + t.description, t.id] } %>
	 <%= f.select :estado_id, @estados, {:include_blank => true} %>
  </div>
  <div class="actions">
    <%= f.submit :value => "Guardar Rol de usuario", :class => "boton", :op => "1" %>
  </div>
<% end %>

app/views/rolagents/edit.html.erb
<h1>Editando Rol de Usuario</h1>

<%= render 'form' %>

app/views/rolagents/index.html.erb
<h1>Roles de los Miembros</h1>
<p id="notice"><%= notice %></p>

<% if current_user %>
   
	<% if is_admin || is_admin_UO || is_secre %>
	   
		<br />
		<span class="nuevo">
		<% if @search %>
		<%= link_to 'Nuevo Rol de Usuario', :controller => "rolagents", :action => "new", :op => @search %>
		<% else %>
		<%= link_to 'Nuevo Rol de Usuario', new_rolagent_path + '/' + params[:id].to_s + '/' + params[:u].to_s %>
		<% end %>
		</span>
		<br />
		<br />

	<% end %>

<% end %>

<table>
  <tr>
    <th>Rol</th>
    <th>Usuario</th>
    <th>Unidad Organizativa</th>
    <th>Comisión</th>
    <th>Fecha de Alta</th>
    <th>Estado</th>
    <th>Ver Datos</th>
   <% if is_admin || is_admin_UO || is_secre %>
    <th>Modificar</th>
    <th>Eliminar</th>
   <% end %>
  </tr>

<% @rolagents.each do |rolagent| %>
  <tr>
    <td><%= rolagent.rol.description %></td>
    <td><%= rolagent.agent.usuario %></td>
    <td><%= rolagent.unit.nombre %></td>
    <td><%= rolagent.commission.nombre %></td>
    <td><%= rolagent.fechaalta %></td>
<!--    <td><#%= rolagent.fechabaja %></td>
    <td><#%= rolagent.motivobaja %></td>-->
    <td><%= rolagent.estado.description %></td>
    <td><%= link_to link_to image_tag("icons/view.png", :width => "25px"), rolagent %></td>
    <% if is_admin || is_admin_UO || is_secre %>
       <td><%= link_to link_to image_tag("icons/edit.png", :width => "25px"), edit_rolagent_path(rolagent) %></td>
       <td><%= link_to link_to image_tag("icons/delete.png", :width => "25px"), rolagent, :confirm => '¿Está Seguro?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>

</table>
<br>
<span class="nuevo">
<% if @searchbycomm %>
<%= link_to 'Volver', commissions_path + "/" + params[:id] %> 
<% else %>
<%= link_to 'Volver', agents_path %> 
<% end %>
</span>

app/views/rolagents/new.html.erb
<h1>Nuevo Rol de Usuario</h1>

<%= render 'form' %>

app/views/rolagents/show.html.erb
<p id="notice"><%= notice %></p>

<table class="show">
<tr>
  <th>Rol:</th>
  <td><%= @rolagent.rol.description %></td>
</tr>

<tr>
  <th>Usuario:</th>
  <td><%= @rolagent.agent.usuario %></td>
</tr>

<tr>
  <th>Unidad Organizativa:</th>
  <td><%= @rolagent.unit.nombre %></td>
</tr>

<tr>
  <th>Comisión:</th>
  <td><%= @rolagent.commission.nombre %></td>
</tr>

<tr>
  <th>Fecha de Alta:</th>
  <td><%= @rolagent.fechaalta %></td>
</tr>

<tr>
  <th>Fecha de Baja:</th>
  <td><%= @rolagent.fechabaja %></td>
</tr>

<tr>
  <th>Motivo de la Baja:</th>
  <td><%= @rolagent.motivobaja %></td>
</tr>

<tr>
  <th>Estado:</th>
  <td><%= @rolagent.estado.description %></td>
</tr>
</table>
<br>
<!--#%= link_to 'Volver', "/rolagents/search/" +  %-->
<span class="nuevo">
<% if @searchbycomm %>
<%= link_to 'Volver', rolagents_path + "/searchbycomm/" +  @rolagent.commission.id.to_s%> 
<% else %>
<%= link_to 'Volver', rolagents_path + "/search/" + @rolagent.agent.id.to_s%> 
<% end %>
</span>