config/routes.rb
Gesco::Application.routes.draw do 
  resources :rolagents

  resources :attendants

  resources :meetings

  resources :docs

  resources :commissions

  resources :units

  resources :agents

  resources :values
	

   root :to => "user_sessions#new"

  Gesco::Application.routes.draw do
    resources :agents, :user_sessions, :rolagents, :attendants, :commissions
    match 'login' => 'user_sessions#new', :as => :login
    match 'logout' => 'user_sessions#destroy', :as => :logout
    match 'rolagents/search/:id' => 'rolagents#search'
    match 'attendants/search/:id' => 'attendants#search'
    match 'commissions/pdf/:id/:a' => 'commissions#pdf'
    match 'commissions/searchbyunit/:id' => 'commissions#searchbyunit'
    match 'rolagents/searchbycomm/:id' => 'rolagents#searchbycomm'
    match 'rolagents/searchbycomm/:id/:u' => 'rolagents#searchbycomm'
    match 'meetings/searchbycomm/:id' => 'meetings#searchbycomm'
    match 'docs/searchbycomm/:id' => 'docs#searchbycomm'
    match 'docs/searchbymeet/:id' => 'docs#searchbymeet'
    match 'commissions/new/:id' => 'commissions#new'
    match 'meetings/new/:id' => 'meetings#new'
    match 'rolagents/new/:id/:u' => 'rolagents#new'
    match 'docs/new/:id' => 'docs#new'
    match 'docs/new/:id' => 'docs#new'
  end

end

app/models/agent.rb
# -*- encoding : utf-8 -*-
class Agent < ActiveRecord::Base
  belongs_to :tipo, :class_name => "Value"
  belongs_to :estado, :class_name => "Value"
  belongs_to :tipodoc, :class_name => "Value"
  belongs_to :tipoauth, :class_name => "Value"
  has_many :attendants
#  belongs_to :rolagent, :class_name => "rolagent"
  
  acts_as_authentic do |c|
    c.login_field=:usuario
    c.logged_in_timeout = 30.minutes
  end

  def dn
    "cn=#{self.email},ou=people,dc=mydomain"
  end

  def password_correcta?(password_plaintext)
#    ldap = LdapConnect.new.ldap
#       ldap.auth self.dn, password_plaintext
#        if (ldap.bind) # will return false if authentication is NOT successful
#          return true
#        end
    return valid_password?(password_plaintext)
  end
end

app/models/attendant.rb
# -*- encoding : utf-8 -*-
class Attendant < ActiveRecord::Base
  belongs_to :meeting
  belongs_to :agent
  belongs_to :estado, :class_name => "Value"
  belongs_to :ausencia, :class_name => "Value"
end

app/models/commission.rb
# -*- encoding : utf-8 -*-
class Commission < ActiveRecord::Base
  belongs_to :tipo, :class_name => "Value"
  belongs_to :estado, :class_name => "Value"
  belongs_to :unidad, :class_name => "Unit"
  belongs_to :visibilidad, :class_name => "Value"
  has_many :docs
end

app/models/doc.rb
# -*- encoding : utf-8 -*-
class Doc < ActiveRecord::Base
  belongs_to :commission
  has_many :meetings
end

app/models/ldap_connect.rb
# -*- encoding : utf-8 -*-
class LdapConnect

  attr_reader :ldap

  def initialize(params = {})
    ldap_config = YAML.load_file("#{RAILS_ROOT}/config/ldap.yml")[RAILS_ENV]
    ldap_options = params
    ldap_options[:encryption] = :simple_tls if ldap_config["ssl"]
    
    @ldap = Net::LDAP.new(ldap_options)
    @ldap.host = ldap_config["host"]
    @ldap.port = ldap_config["port"]
    @ldap.base = ldap_config["base"]
    @ldap.auth ldap_config["admin_user"], ldap_config["admin_password"] if params[:admin] 
  end

end

app/models/meeting.rb
# -*- encoding : utf-8 -*-
class Meeting < ActiveRecord::Base
  belongs_to :commission
  belongs_to :estado, :class_name => "Value"
  belongs_to :doc
  has_many :attendants
end

app/models/rolagent.rb
# -*- encoding : utf-8 -*-
class Rolagent < ActiveRecord::Base
  belongs_to :rol, :class_name => "Value"
  belongs_to :agent
  belongs_to :unit
  belongs_to :commission
  belongs_to :estado, :class_name => "Value"
end

app/models/unit.rb
# -*- encoding : utf-8 -*-
class Unit < ActiveRecord::Base
	has_many :commissions
end

app/models/user_session.rb
# -*- encoding : utf-8 -*-
class UserSession < Authlogic::Session::Base
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end
  authenticate_with Agent
  verify_password_method :password_correcta?
end

app/models/value.rb
# -*- encoding : utf-8 -*-
class Value < ActiveRecord::Base
	has_many :agents
	has_many :commissions
	has_many :attendants
	has_many :rolagents
end

app/controllers/docs_controller.rb
# -*- encoding : utf-8 -*-
class DocsController < ApplicationController
  # GET /docs
  # GET /docs.xml
  def index
    @docs = Doc.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @docs }
    end
  end

  # GET /docs/1
  # GET /docs/1.xml
  def show
    @doc = Doc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @doc }
    end
  end
  
  def searchbycomm
     unless current_user.nil?
        @searchbycomm = params[:id];
        @docs = Doc.find(:all, :conditions => {:commission_id => params[:id] })
        render :index
     else 
      redirect_to_login
     end
  end


  def searchbymeet
     unless current_user.nil?
	  	  @meet_docs = Meeting.find(:all, :conditions => {:id => params[:id]})
		  vacio = true
		  @meet_docs.each do |met|
		     unless met.doc.nil?
			     vacio = false
		     end
		  end
		  unless vacio
  		     @meet_docs = @meet_docs.map {|m| [m.doc.id]}  
   	     @docs = Doc.find(:all, :conditions => {:id => @meet_docs})
		  else
		  	 @docs = nil
		  end
        render :index
     else 
      redirect_to_login
     end
  end

  # GET /docs/new
  # GET /docs/new.xml
  def new
    @doc = Doc.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @doc }
    end
  end

  # GET /docs/1/edit
  def edit
    @doc = Doc.find(params[:id])
  end

  # POST /docs
  # POST /docs.xml
  def create
    @doc = Doc.new(params[:doc])
    tmp = @doc.url.tempfile
	 time = Time.new
	 dir = 'public/uploads/' + time.year.to_s + '/' + time.month.to_s + '/' + @doc.commission.nombre.gsub(' ', '').downcase + '/' + '.pdf'
	 FileUtils.mkdir_p(File.dirname(dir)) unless File.exists?(dir)
    file = File.join(Rails.root, "public", "uploads", time.year.to_s, time.month.to_s, @doc.commission.nombre.gsub(' ', '').downcase, @doc.url.original_filename)
    FileUtils.cp tmp.path, file
    FileUtils.rm tmp.path

  	 @doc.url = '/uploads/' + time.year.to_s + '/' + time.month.to_s + '/' + @doc.commission.nombre.gsub(' ', '').downcase + '/'  + @doc.url.original_filename
    respond_to do |format|
      if @doc.save
        format.html { redirect_to(docs_path + "/searchbycomm/" + @doc.commission.id.to_s, :notice => 'Documentación creada satisfactoriamente.') }
        format.xml  { render :xml => @doc, :status => :created, :location => @doc }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @doc.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /docs/1
  # PUT /docs/1.xml
  def update
    @doc = Doc.find(params[:id])

    respond_to do |format|
      if @doc.update_attributes(params[:doc])
        format.html { redirect_to(docs_path + "/searchbycomm/" + @doc.commission.id.to_s, :notice => 'Documentación editada satisfactoriamente.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @doc.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.xml
  def destroy
    @doc = Doc.find(params[:id])
    @doc.destroy

    respond_to do |format|
      format.html { redirect_to(:back) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/agents_helper.rb
# -*- encoding : utf-8 -*-
module AgentsHelper
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/helpers/attendants_helper.rb
# -*- encoding : utf-8 -*-
module AttendantsHelper
end

app/helpers/commissions_helper.rb
# -*- encoding : utf-8 -*-
module CommissionsHelper
end

app/helpers/docs_helper.rb
# -*- encoding : utf-8 -*-
module DocsHelper
end

app/helpers/meetings_helper.rb
# -*- encoding : utf-8 -*-
module MeetingsHelper
end

app/helpers/rolagents_helper.rb
# -*- encoding : utf-8 -*-
module RolagentsHelper
end

app/helpers/units_helper.rb
# -*- encoding : utf-8 -*-
module UnitsHelper
end

app/helpers/values_helper.rb
# -*- encoding : utf-8 -*-
module ValuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gesco</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="cabecera">
<div class="logo">
<%= link_to image_tag("logo.gif"), root_path %> 
<!--<img src="/images/logo.gif" />-->
</div>
<div class="titulo">
Gestor de Comisiones
<br />
Universidad de La Laguna
</div>
<%= render :partial => '/shared/logged' %> 
<%= render :partial => '/shared/bread_crumbs' %> 

</div>



<div class="centro">
<%= render :partial => '/shared/menu' %> 

<%= yield %>

</div>

<div class="pie">
Licenciado bajo
<%= link_to "AGPLv3", "http://www.gnu.org/licenses/agpl-3.0.html" %>
, se puede
<%= link_to "descargar libremente", "https://gitorious.org/mencey/gesco" %>
</div>


</body>
</html>

app/views/shared/_bread_crumbs.html.erb
<div class="breadcrumbs">
<% url = breadcrumbs = get_bread_crumb %>

<%= link_to 'Inicio', '/' %>

<% lista = '' %>
<% breadcrumbs.each do |b| %>
	<% lista += b.to_s + '/' %>
	<% texto = traduce(b) %>
	<% unless b.include?('search') %>
		<%= link_to texto, lista %>
	<% end %>
	<% if b != request.request_uri.split('/').last  and !b.include?('search')%>
		> 
	<% end %>
<% end %>

</div>

app/views/shared/_logged.html.erb
<div class="logged">
   <% if current_user %>
      <%= link_to (current_user.nombre + " " + current_user.apellido1), '/agents/' + current_user.id.to_s %>
      <%= link_to "(Salir)", :logout%>
   <% end %>
</div>

app/views/shared/_menu.html.erb
<div class="menu">
<div class="submenu">
<% if current_user %>
   <%= link_to 'Usuarios |', agents_path if is_admin || is_admin_UO || is_secre  %>
<!--  <#%= link_to 'Mis datos |', agents_path unless is_admin || is_admin_UO || is_secre %>  -->
   <%= link_to 'Unidades Organizativas |', units_path  if is_admin %>
   <%= link_to 'Unidades Organizativas |', units_path  unless is_admin %>
<!--  <#%= link_to 'Roles |', rolagents_path  if is_admin || is_admin_UO || is_secre %>  
   <#%= link_to 'Comisiones |', commissions_path  if is_admin || is_admin_UO || is_secre %> 
   <#%= link_to 'Mis Comisiones |', commissions_path  unless is_admin || is_admin_UO || is_secre %> 
      <#%= link_to 'Documentación |', docs_path %> 
   <#%= link_to 'Reuniones |', meetings_path  if is_admin || is_admin_UO || is_secre %> 
   <#%= link_to 'Mis Reuniones |', meetings_path  unless is_admin || is_admin_UO || is_secre %> 
   <#%= link_to 'Asistentes |', attendants_path  if is_admin || is_admin_UO || is_secre %> -->
   <%= link_to 'Tabla de valores |', values_path  if is_admin %>

<% else %>
   <%= link_to 'Acceso', :login %>
<% end %>
</div>

</div>