config/routes.rb
Gesco::Application.routes.draw do 
  resources :rolagents

  resources :attendants

  resources :meetings

  resources :docs

  resources :commissions

  resources :units

  resources :agents

  resources :values
	

   root :to => "user_sessions#new"

  Gesco::Application.routes.draw do
    resources :agents, :user_sessions, :rolagents, :attendants, :commissions
    match 'login' => 'user_sessions#new', :as => :login
    match 'logout' => 'user_sessions#destroy', :as => :logout
    match 'rolagents/search/:id' => 'rolagents#search'
    match 'attendants/search/:id' => 'attendants#search'
    match 'commissions/pdf/:id/:a' => 'commissions#pdf'
    match 'commissions/searchbyunit/:id' => 'commissions#searchbyunit'
    match 'rolagents/searchbycomm/:id' => 'rolagents#searchbycomm'
    match 'rolagents/searchbycomm/:id/:u' => 'rolagents#searchbycomm'
    match 'meetings/searchbycomm/:id' => 'meetings#searchbycomm'
    match 'docs/searchbycomm/:id' => 'docs#searchbycomm'
    match 'docs/searchbymeet/:id' => 'docs#searchbymeet'
    match 'commissions/new/:id' => 'commissions#new'
    match 'meetings/new/:id' => 'meetings#new'
    match 'rolagents/new/:id/:u' => 'rolagents#new'
    match 'docs/new/:id' => 'docs#new'
    match 'docs/new/:id' => 'docs#new'
  end

end

app/models/commission.rb
# -*- encoding : utf-8 -*-
class Commission < ActiveRecord::Base
  belongs_to :tipo, :class_name => "Value"
  belongs_to :estado, :class_name => "Value"
  belongs_to :unidad, :class_name => "Unit"
  belongs_to :visibilidad, :class_name => "Value"
  has_many :docs
end

app/controllers/commissions_controller.rb
# -*- encoding : utf-8 -*-
class CommissionsController < ApplicationController


  # GET /commissions
  # GET /commissions.xml
  def index
  	 unless current_user.nil?
	  	 if is_admin || is_admin_UO
  		  	@commissions = Commission.all
		 else 
		 	@roles = Rolagent.find(:all, :conditions => {:agent_id => current_user.id}).map { |r| [r.commission.nombre]}
		 	@units = Rolagent.find(:all, :conditions => {:agent_id => current_user.id}).map { |r| [r.unit.id]}
  	  		@commissions = Commission.find(:all, :conditions => {nombre =>  @roles, :unidad_id => @units})

            respond_to do |format|
              format.html # index.html.erb
              format.xml  { render :xml => @commissions }
            end
         end
     else 
      redirect_to_login
    end
  end
  
  def searchbyunit
     unless current_user.nil?
        if is_admin || is_admin_UO
            @commissions = Commission.find(:all, :conditions => [ 'id != 0 AND unidad_id = ?', params[:id] ]) 
        else 
            @roles = Rolagent.find(:all, :conditions => {:agent_id => current_user.id}).map { |r| [r.commission.nombre]}
            @units = Rolagent.find(:all, :conditions => {:agent_id => current_user.id}).map { |r| [r.unit.id]}
            @id = Commission.find(:all, :conditions => [ 'id != 0 AND unidad_id = ?', params[:id] ]).map { |r| [r.id]}
            @commissions = Commission.find(:all, :conditions => {:id => @id, :nombre =>  @roles, :unidad_id => @units})
        end
        render :index
     else 
      redirect_to_login
     end
  end
    


  # GET /pdf/:id/:agent.pdf
  def pdf
	 unless params[:id].nil? and params[:a].nil? then
	 	 @rol = Rolagent.find(:all, :conditions => {:agent_id => params[:a], :commission_id => params[:id]}).map { |r| [r.commission_id] }
		 unless @rol.nil? or @rol.empty? then
		    @commission = Commission.find(:first, :conditions => {:id => @rol})

			 @valor = Value.find(:first, :conditions => {:codigo =>  "6.3"})
			 @secretario = Rolagent.find(:first, :conditions => {:commission_id => params[:id], :rol_id => @valor.id})

			 @agent = Agent.find(:first, :conditions => {:id => params[:a]})

			 @periodo = Rolagent.find(:first, :conditions => {:commission_id => params[:id], :agent_id => params[:a]})

			 @totales = Meeting.find(:all, :conditions => {:commission_id => params[:id]}).size
			 @reuniones = Meeting.find(:all, :conditions => {:commission_id => params[:id]}).map { |r| [r.id]}
			 @no = Value.find(:first, :conditions => {:codigo =>  "14.3"})
			 @asiste = Attendant.find(:all, :conditions => {:agent_id => params[:a], :meeting_id => @reuniones, :ausencia_id => @no.id}).size

			 render :show
		 else 
		 	redirect_to_login
		 end
	  end
  end

  # GET /commissions/1
  # GET /commissions/1.xml
  def show
    @commission = Commission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
		format.pdf {render :layout => false}
     format.xml  { render :xml => @commission }
    end
  end

  # GET /commissions/new
  # GET /commissions/new.xml
  def new
    unless current_user.nil?
      if is_admin_UO || is_admin
        @commission = Commission.new
  
        respond_to do |format|
          format.html # new.html.erb
          format.xml  { render :xml => @commission }
        end
      else 
        render_500
      end
    else
      redirect_to_login
    end
  end

  # GET /commissions/1/edit
  def edit
    unless current_user.nil?
      if is_admin_UO || is_admin
        @commission = Commission.find(params[:id])
        #@meetings = Meeting.find_by_commission_id(@commission.id)
        #@roles = Rolagent.find_by_commission_id(@commission.id)
        #@agents = Agent.find_by_id(@roles.agent)
        #@docs = Doc.find_by_commission_id(@commission.id)
      else 
        render_500
      end
    else
      redirect_to_login
    end
  end

  # POST /commissions
  # POST /commissions.xml
  def create
    unless current_user.nil?
      if is_admin_UO || is_admin
        @commission = Commission.new(params[:commission])
    
        respond_to do |format|
          if @commission.save
            format.html { redirect_to(commissions_path + "/searchbyunit/" + @commission.unidad.id.to_s, :notice => 'Comisión creada satisfactoriamente.') }
            format.xml  { render :xml => @commission, :status => :created, :location => @commission }
          else
            format.html { render :action => "new" }
            format.xml  { render :xml => @commission.errors, :status => :unprocessable_entity }
          end
        end
      else 
        render_500
      end
    else
      redirect_to_login
    end
  end

  # PUT /commissions/1
  # PUT /commissions/1.xml
  def update
    unless current_user.nil?
      if is_admin_UO || is_admin
        @commission = Commission.find(params[:id])
    
        respond_to do |format|
          if @commission.update_attributes(params[:commission])
            format.html { redirect_to(@commission, :notice => 'Comisión editada satisfactoriamente.') }
            format.xml  { head :ok }
          else
            format.html { render :action => "edit" }
            format.xml  { render :xml => @commission.errors, :status => :unprocessable_entity }
          end
        end
      else 
        render_500
      end
    else
      redirect_to_login
    end
  end

  # DELETE /commissions/1
  # DELETE /commissions/1.xml
  def destroy
    unless current_user.nil?
      if is_admin_UO || is_admin
        @commission = Commission.find(params[:id])
        @commission.destroy
        respond_to do |format|
          format.html { redirect_to(:back) }
          format.xml  { head :ok }
        end
      else 
        render_500
      end
    else
      redirect_to_login
    end
  end
end

app/helpers/commissions_helper.rb
# -*- encoding : utf-8 -*-
module CommissionsHelper
end

app/views/commissions/_agent.html.erb
<h1>Listado de usuarios</h1>

<%= link_to 'Añadir nuevo usuario', new_agent_path %>

<br />
<table>
  <tr>
    <th>Nombre</th>
    <th>Apellido1</th>
    <th>Email1</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% if @agents.kind_of?(Array) then %>

<% @agents.each do |agent| %>
  <tr>
<!--    <td><%#= agent.tipo.description %></td>
    <td><%#= agent.estado.description %></td>-->
    <td><%= agent.nombre %></td>
    <td><%= agent.apellido1 %></td>
<!--    <td><%#= agent.apellido2 %></td>
    <td><%#= agent.tipodoc.description %></td>
    <td><%#= agent.numdoc %></td>-->
    <td><%= agent.email1 %></td>
<!--    <td><%#= agent.email2 %></td>
    <td><%#= agent.telefono1 %></td>
    <td><%#= agent.telefono2 %></td>
    <td><%#= agent.tipoauth.description %></td>
    <td><%#= agent.usuario %></td>
    <td><%#= agent.password %></td>
    <td><%#= agent.serverimap %></td>
    <td><%#= agent.serverldap %></td>
    <td><%#= agent.baseldap %></td>
    <td><%#= agent.rolagent %></td> -->
    <td><%= link_to image_tag("icons/view.png", :width => "25px"), agent %></td>
    <td><%= link_to image_tag("icons/edit.png", :width => "25px"), edit_agent_path(agent) %></td>
    <td><%= link_to image_tag("icons/delete.png", :width => "25px"), agent, :confirm => '¿Está Seguro?', :method => :delete %></td>
  </tr>
<% end %>

<% else %>
  <% agent = @agents %>
  <tr>
<!--    <td><%#= agent.tipo.description %></td>
    <td><%#= agent.estado.description %></td>-->
    <td><%= agent.nombre %></td>
    <td><%= agent.apellido1 %></td>
<!--    <td><%#= agent.apellido2 %></td>
    <td><%#= agent.tipodoc.description %></td>
    <td><%#= agent.numdoc %></td>-->
    <td><%= agent.email1 %></td>
<!--    <td><%#= agent.email2 %></td>
    <td><%#= agent.telefono1 %></td>
    <td><%#= agent.telefono2 %></td>
    <td><%#= agent.tipoauth.description %></td>
    <td><%#= agent.usuario %></td>
    <td><%#= agent.password %></td>
    <td><%#= agent.serverimap %></td>
    <td><%#= agent.serverldap %></td>
    <td><%#= agent.baseldap %></td>
    <td><%#= agent.rolagent %></td> -->
    <td><%= link_to image_tag("icons/view.png", :width => "25px"), agent %></td>
    <td><%= link_to image_tag("icons/edit.png", :width => "25px"), edit_agent_path(agent) %></td>
    <td><%= link_to image_tag("icons/delete.png", :width => "25px"), agent, :confirm => '¿Está Seguro?', :method => :delete %></td>
  </tr>
<%end %>
</table>

app/views/commissions/_doc.html.erb
<h1>Listado de Documentación</h1>

<%= link_to 'Nueva documentación', new_doc_path %>

<br />
<table>
  <tr>
    <th>Commission</th>
    <th>Descargar</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


<% if @agents.kind_of?(Array) then %>

<% @docs.each do |doc| %>
  <tr>
    <td><%= doc.commission.nombre %></td>
    <td><%= link_to image_tag("icons/download.png", :width => "25px"), doc.url , {:target => "_blank"} %>
	 <%= doc.url %></td>
    <td><%= link_to image_tag("icons/view.png", :width => "25px"), doc %></td>
    <td><%= link_to image_tag("icons/edit.png", :width => "25px"), edit_doc_path(doc) %></td>
    <td><%= link_to image_tag("icons/delete.png", :width => "25px"), doc, :confirm => '¿Está Seguro?', :method => :delete %></td>
  </tr>
<% end %>

<% else %>
	<% doc = @docs %>

  <tr>
    <td><%= doc.commission.nombre %></td>
    <td><%= link_to image_tag("icons/download.png", :width => "25px"), doc.url , {:target => "_blank"} %>
	 <%= doc.url %></td>
    <td><%= link_to image_tag("icons/view.png", :width => "25px"), doc %></td>
    <td><%= link_to image_tag("icons/edit.png", :width => "25px"), edit_doc_path(doc) %></td>
    <td><%= link_to image_tag("icons/delete.png", :width => "25px"), doc, :confirm => '¿Está Seguro?', :method => :delete %></td>
  </tr>


<% end %>
</table>

app/views/commissions/_form.html.erb
<%= form_for(@commission, :html => { :class => "formulario"}) do |f| %>
  <% if @commission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commission.errors.count, "error") %> prohibited this commission from being saved:</h2>

      <ul>
      <% @commission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Tipo" %><br />
	 <% @tipos = Value.find(:all, :conditions => 'codigo like "2._"').map { |t| [t.codigo + ', ' + t.description, t.id] } %>
	     <%= f.select :tipo_id, @tipos, {:include_blank => true} %>

  </div>
  <div class="field">
    <%= f.label "Estado" %><br />
	 <% @estados = Value.find(:all, :conditions => 'codigo like "3._"').map { |t| [t.codigo + ', ' + t.description, t.id] } %>
	     <%= f.select :estado_id, @estados, {:include_blank => true} %>
  </div>
  <div class="field">
    <%= f.label "Unidad" %><br />
	 <% unless params[:id].nil? %>
	 <% @unidades = Unit.find(:all, :conditions => {:id => params[:id]} ).map { |t| [t.nombre, t.id] } %>
	     <%= f.select :unidad_id, @unidades %>
	 <% else %>
	 <% @unidades = Unit.find(:all).map { |t| [t.nombre, t.id] } %>
	     <%= f.select :unidad_id, @unidades, {:include_blank => true}  %>
	 <% end %>
  </div>
  <div class="field">
    <%= f.label "Nombre" %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label "Nombre Completo" %><br />
    <%= f.text_area :nombrelargo %>
  </div>
  <div class="field">
    <%= f.label "Funciones" %><br />
    <%= f.text_area :funciones %>
  </div>
  <div class="field">
    <%= f.label "Fecha de Creación" %><br />
    <%= f.datetime_select :fechacreacion %>
  </div>
  <div class="field">
    <%= f.label "Fecha de Baja" %><br />
    <%= f.datetime_select :fechabaja, {:include_blank => true} %>
  </div>
  <div class="field">
    <%= f.label "Motivo de Baja" %><br />
    <%= f.text_area :motivobaja %>
  </div>
  <div class="field">
    <%= f.label "Composición" %><br />
    <%= f.text_area :composicion %>
  </div>
  <div class="field">
    <%= f.label "Visibilidad" %><br />
	 <% @visibilidades = Value.find(:all, :conditions => 'codigo like "4._"').map { |t| [t.codigo + ', ' + t.description, t.id] } %>
	 <%= f.select :visibilidad_id, @visibilidades, {:include_blank => true} %>
  </div>
  <div class="actions">
    <%= f.submit :value => "Guardar Comisión", :class => "boton" %>
  </div>
<% end %>

app/views/commissions/_meeting.html.erb
<h1>Reuniones</h1>

<% if @meetings %>
<table>
  <tr>
    <th>Commission</th>
    <th>Estado</th>
    <th>Fechainicio</th>
    <th>Ordendia</th>
    <th>Acta</th>
    <th>Fechaaprobacion</th>
    <th>Lugar</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

   <% if @meetings.kind_of?(Array) then %>
      <% @meetings.each do |meeting| %>
        <tr>
          <td><%= meeting.commission.nombre %></td>
          <td><%= meeting.estado.description %></td>
          <td><%= meeting.fechainicio %></td>
          <td><%= meeting.lugar %></td>
          <td><%= link_to image_tag("icons/view.png", :width => "25px"), meeting %></td>
          <td><%= link_to image_tag("icons/edit.png", :width => "25px"), edit_meeting_path(meeting) %></td>
          <td><%= link_to image_tag("icons/delete.png", :width => "25px"), meeting, :confirm => '¿Está Seguro?', :method => :delete %></td>
        </tr>
      <% end %>
   <% else %>
      <% meeting = @meetings %>
         <tr>
          <td><%= meeting.commission.nombre %></td>
          <td><%= meeting.estado.description %></td>
          <td><%= meeting.fechainicio %></td>
          <td><%= meeting.lugar %></td>
          <td><%= link_to image_tag("icons/view.png", :width => "25px"), meeting %></td>
          <td><%= link_to image_tag("icons/edit.png", :width => "25px"), edit_meeting_path(meeting) %></td>
          <td><%= link_to image_tag("icons/delete.png", :width => "25px"), meeting, :confirm => '¿Está Seguro?', :method => :delete %></td>
        </tr>
   <% end %>

</table>
<% else %>
<table>
   <tr>
      <td> No hay reuniones a mostrar </td>
   </tr>
</table>
<% end %>
<br />
<span class="nuevo">
   <%= link_to 'Nueva Reunión', new_meeting_path %>
</span>

app/views/commissions/edit.html.erb
<h1>Editando Comisiones</h1>

<%= render 'form' %>

app/views/commissions/index.html.erb
<h1>Listado de Comisiones</h1>
<p id="notice"><%= notice %></p>
<% if is_admin || is_admin_UO %>
<br />
   <span class="nuevo">
   <%= link_to 'Nueva Comisión', new_commission_path + '/' + params[:id] %>
   </span>
<br />
<br />
<% end %>

<table>
  <tr>
    <th>Estado</th>
    <th>Unidad</th>
    <th>Nombre</th>
    <th>Fecha Creación</th>
    <th>Entrar</th>
    <th>Generar Informe</th>
<% if is_admin || is_admin_UO %>
    <th>Eliminar</th>
<% end %>
  </tr>

<% @commissions.each do |commission| %>
  <tr>
    <td><%= commission.estado.description %></td>
    <td><%= commission.unidad.nombre %></td>
    <td><%= commission.nombre %></td>
    <td><%= commission.fechacreacion %></td>
    <td><%= link_to image_tag("icons/view.png", :width => "25px"), commission %></td>
        
    <td>
      <% @R = Rolagent.find(:all, :conditions => ['agent_id == ? AND commission_id == ? AND unit_id == ?',current_user.id,commission.id,commission.unidad.id]) %>
      <% if @R[0] %>
      <%= link_to image_tag("icons/informes.png", :width => "25px"), root_path + "commissions/pdf/"+commission.id.to_s+"/" + current_user.id.to_s+".pdf" %>
      <% else %>
      <%= "No Perteneces" %>
      <% end %>
    
    </td>




   <% if is_admin || is_admin_UO %>
     <td><%= link_to image_tag("icons/delete.png", :width => "25px"), commission, :confirm => '¿Está Seguro?', :method => :delete %></td>
   <% end %>
  </tr>
<% end %>
</table>

<br/>
<span class="nuevo">
<%= link_to 'Volver', units_path + "/" + params[:id] %> 
</span>

app/views/commissions/new.html.erb
<h1>Nueva Comisión</h1>

<%= render 'form' %>

app/views/commissions/show.html.erb
<h1> Información Básica de la Comisión </h1>

<p id="notice"><%= notice %></p>

<table class="show">
<tr>
<th>Tipo:</th>
<td><%= @commission.tipo.description %></td>
</tr>

<tr>
<th>Estado:</th>
<td><%= @commission.estado.description %></td>
</tr>

<tr>
<th>Unidad:</th>
<td><%= @commission.unidad.nombre %></td>
</tr>

<tr>
<th>Nombre:</th>
<td><%= @commission.nombre %></td>
</tr>

<tr>
<th>Nombre Completo:</th>
<td><%= @commission.nombrelargo %></td>
</tr>

<tr>
<th>Funciones:<br></th>
<td><%= @commission.funciones %></td>
</tr>

<tr>
<th>Fecha Creación:</th>
<td><%= @commission.fechacreacion %></td>
</tr>

<tr>
<th>Fecha Baja:</th>
<td><%= @commission.fechabaja %></td>
</tr>

<tr>
<th>Motivo Baja:<br></th>
<td><%= @commission.motivobaja %></td>
</tr>

<tr>
<th>Composición:<br></th>
<td><%= @commission.composicion %></td>
</tr>


</table>
<br />
<br />

<% if is_admin || is_admin_UO %>

<span class="nuevo">
   <%= link_to 'Editar Datos Básicos de la Comisión', edit_commission_path(@commission) %>
</span>
<br />
<br />

<% end %>

<span class="nuevo">
   <%= link_to 'Ver Miembros', rolagents_path + "/searchbycomm/" + params[:id] + '/' +  @commission.unidad.id.to_s %>
</span>

<br />
<br />


<span class="nuevo">
   <%= link_to 'Ver Reuniones', meetings_path + "/searchbycomm/" + params[:id] %>
</span>

<br />
<br />

<span class="nuevo">
   <%= link_to 'Ver Documentos', docs_path + "/searchbycomm/" + params[:id] %>
</span>

<br />
<br />
<span class="nuevo">
<%= link_to 'Volver', commissions_path + "/searchbyunit/" +  @commission.unidad.id.to_s%> 
</span>