config/routes.rb
Gesco::Application.routes.draw do 
  resources :rolagents

  resources :attendants

  resources :meetings

  resources :docs

  resources :commissions

  resources :units

  resources :agents

  resources :values
	

   root :to => "user_sessions#new"

  Gesco::Application.routes.draw do
    resources :agents, :user_sessions, :rolagents, :attendants, :commissions
    match 'login' => 'user_sessions#new', :as => :login
    match 'logout' => 'user_sessions#destroy', :as => :logout
    match 'rolagents/search/:id' => 'rolagents#search'
    match 'attendants/search/:id' => 'attendants#search'
    match 'commissions/pdf/:id/:a' => 'commissions#pdf'
    match 'commissions/searchbyunit/:id' => 'commissions#searchbyunit'
    match 'rolagents/searchbycomm/:id' => 'rolagents#searchbycomm'
    match 'rolagents/searchbycomm/:id/:u' => 'rolagents#searchbycomm'
    match 'meetings/searchbycomm/:id' => 'meetings#searchbycomm'
    match 'docs/searchbycomm/:id' => 'docs#searchbycomm'
    match 'docs/searchbymeet/:id' => 'docs#searchbymeet'
    match 'commissions/new/:id' => 'commissions#new'
    match 'meetings/new/:id' => 'meetings#new'
    match 'rolagents/new/:id/:u' => 'rolagents#new'
    match 'docs/new/:id' => 'docs#new'
    match 'docs/new/:id' => 'docs#new'
  end

end

app/models/unit.rb
# -*- encoding : utf-8 -*-
class Unit < ActiveRecord::Base
	has_many :commissions
end

app/controllers/units_controller.rb
# -*- encoding : utf-8 -*-
class UnitsController < ApplicationController
  # GET /units
  # GET /units.xml
  def index
    if is_admin
        @units = Unit.find(:all, :conditions => [ 'id != 0 ' ])
    else
        @id = Rolagent.find(:all, :conditions => {:agent_id => current_user.id}).map { |r| [r.unit.id]}
        @units = Unit.find(:all, :conditions => {:id => @id})
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @units }
    end
  end

  # GET /units/1
  # GET /units/1.xml
  def show
    @unit = Unit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @unit }
    end
  end

  # GET /units/new
  # GET /units/new.xml
  def new
    @unit = Unit.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @unit }
    end
  end

  # GET /units/1/edit
  def edit
    @unit = Unit.find(params[:id])
  end

  # POST /units
  # POST /units.xml
  def create
    @unit = Unit.new(params[:unit])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to(units_path, :notice => 'Unidad organizativa creada satisfactoriamente.') }
        format.xml  { render :xml => @unit, :status => :created, :location => @unit }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @unit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /units/1
  # PUT /units/1.xml
  def update
    @unit = Unit.find(params[:id])

    respond_to do |format|
      if @unit.update_attributes(params[:unit])
        format.html { redirect_to(@unit, :notice => 'Unidad organizativa editada satisfactoriamente.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @unit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.xml
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to(:back) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/units_helper.rb
# -*- encoding : utf-8 -*-
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for(@unit, :html => { :class => "formulario"}) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nombre" %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label "Nombre Completo" %><br />
    <%= f.text_area :nombrelargo %>
  </div>
  <div class="actions">
    <%= f.submit :value => "Guardar Unidad Organizativa", :class => "boton" %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editar Unidad Organizativa</h1>

<%= render 'form' %>

app/views/units/index.html.erb
<h1>Unidades Organizativas</h1>
<p id="notice"><%= notice %></p>

<% if is_admin %>

<br />

<span class="nuevo">
<%= link_to 'Nueva Unidad Organizativa', new_unit_path %>
</span>
<br />
<br />
<%end%>

<table>
  <tr>
    <th>Nombre</th>
    <th>Nombre Completo</th>
    <th>Entrar</th>
    <th>Borrar</th>
  </tr>

<% @units.each do |unit| %>
  <tr>
    <td><%= unit.nombre %></td>
    <td><%= unit.nombrelargo %></td>
    <td><%= link_to link_to image_tag("icons/view.png", :width => "25px"), unit %></td>
    <td><%= link_to link_to image_tag("icons/delete.png", :width => "25px"), unit, :confirm => '¿Está Seguro?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/units/new.html.erb
<h1>Nueva Unidad Organizativa</h1>

<%= render 'form' %>

app/views/units/show.html.erb
<h1> Información Básica de la Unidad Organizativa </h1>

<p id="notice"><%= notice %></p>

<table class="show">
<tr>
  <th>Nombre:</th>
  <td><%= @unit.nombre %></td>
</tr>

<tr>
  <th>Nombre Completo:</th>
  <td><%= @unit.nombrelargo %></td>
</tr>
</table>

<br />
<br />

<% if is_admin %>

<span class="nuevo">
   <%= link_to 'Editar Datos Básicos de la Unidad Organizativa', edit_unit_path(@unit) %>
</span>
<br />
<br />

<% end %>

<span class="nuevo">
   <%= link_to 'Ver Comisiones', commissions_path + "/searchbyunit/" + params[:id] %></td>
</span>

<br />
<br />
<span class="nuevo">
<%= link_to 'Volver', units_path %> 
</span>